language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "node"
  - "lts/*"

matrix:
  fast_finish: true

services:
  - mongodb
  
before_script:
  - sleep 15
  - mongo test --eval 'db.createUser("test", "test");'
